name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js to generate website
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm install marked marked-highlight highlight.js marked-katex-extension
    - name: Generate website
      run: node ./main.js
      working-directory: ./webGenerate/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
